### ISSUE TITLE
No recibo las monedas

### ISSUE THREAD

**Issue by Killaker** [True-Mining/TrueMiningDesktop#11]
Hola, he minado varios dias RVN y siempre las he recibido sin problemas una vez finalizado el tiempo de la ronda, pero desde hace 2 dias no he recibido lo que he minado, cuando finaliza la ronda los puntos RandomX se resetean a 0 pero no recibo nada en mi billetera, no he cambiado nada en la configuracion por lo que no se cual puede ser el problema ya que antes si que funcionaba y recibia los pagos.
Alguna sugerencia?
Gracias!

**Comment by Yoru6678** [comment]
je crois, c'est une arnaque tu reçois ta récompense et après rien

**Comment by matheusbach** [comment]
Hola, perdón por no responder aquí antes. Esta pestaña está más relacionada con el software que con los pagos de la plataforma. Si tiene nuevas preguntas y desea un servicio más rápido, le sugiero que pregunte en nuestro grupo de Telegram (enlace en el software, pestaña "Other Stuff").

Los días 16 y 17 de marzo efectivamente hubo problemas con los pagos de RVN. Estos problemas se resolvieron y estos saldos pendientes se pagaron el día 19.

Agradecemos su comprensión y reforzamos nuestro compromiso de compensar siempre a los usuarios por la minería.

Puede seguir los registros diarios (desde 2019) de pagos y saldos en nuestro canal de transparencia (https://t.me/joinchat/VMjgN8gRaTwwz5gt)
