### ISSUE TITLE
Guia para checkout e instalação local

### ISSUE THREAD

**Issue by ezelorenzatti** [True-Mining/TrueMiningDesktop#3]
Primeiramente adorei a proposta do projeto, já baixei e está minerando. 

Sou programador, atualmente meu foco é Java, mas estou bastante interessado no CSharp.

Caso for possível montar um guia de como montar o ambiente de desenvolvimento isso meu ajudaria muito e acredito que a outros possíveis interessados. 

Eu já fiz o checkout do código, mas confesso que estou bem perdido em iniciar a aplicação devido a dificuldade de instalar algumas dependências, fiz algumas pesquisas mas não avancei muito.

Estou usando VSCode

Segue abaixo, algumas tentativas sem sucesso
![image](https://user-images.githubusercontent.com/33372213/115981303-122cb100-a569-11eb-9412-1ef8bd2bff2d.png)

**Comment by matheusbach** [comment]
Olá. Eu estou usando o Visual Studio Community no Windows por na minha opinião ter um autocomplete mais eficiente e fornecer edição de XAML com visualização em tempo real.
Caso você de toda forma queira usar o VS Code, verifique se você tem o .NET Core versão 3.1 instalada, que é a versão utilizada atualmente. então instale os pacotes com problema usando nuget

**Comment by matheusbach** [comment]
como não há novos comentários, irei fechar a issue
