### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by jubinex** [True-Mining/TrueMiningDesktop#5]
comecei a usa o true mining ontem porem, após uma reiniciação do meu pc o true mining não abre mais tentei de tds as formas inclusive restaurei o sistema e não abre

**Comment by matheusbach** [comment]
Olá. Você verificou se não marcou a caixa de seleção "Start Hide" nas configurações? Se você marcar essa opção o True Mining vai iniciar de forma oculta, aparecendo somente no gerenciador de tarefas e no systray (perto do relógio)

**Comment by matheusbach** [comment]
por falta de retorno irei fechar a issue
