### ISSUE TITLE
tor.exe and privoxy.exe

### ISSUE THREAD

**Issue by hirinhu** [True-Mining/TrueMiningDesktop#7]
Hi Matheus, id like to know why both these process run on TrueMiningDesktop´s background. 

Thank you!

**Comment by matheusbach** [comment]
Hi. [TOR (The Onion Router)](https://torproject.org) and [Privoxy](https://privoxy.org) are open source projects used in True Mining Desktop to bypass firewalls and other types of network blocks that are blocking app from performing the tasks necessary for mining. Tor initiates a connection to the onion network to pass traffic encrypted through some network nodes until it reaches its final destination, changing aparent destination IP and bypassing some firewalls. Privoxy takes care of creating an http interface to facilitate True Mining Desktop communication with the socks5 interface that is generated by tor.exe.
By default these processes are not run on your machine, but come into if software cannot access some network addresses that are needed for mining, so it makes this attempt using the method I described above. If you disable the firewall they probably won't show up to you.

**Comment by matheusbach** [comment]
Irei fechar a issue por inatividade. Caso tenha mais alguma dúvida pode comentar

**Comment by matheusbach** [comment]
Irei fechar a issue por inatividade. Caso tenha mais alguma dúvida pode comentar
